### ISSUE TITLE
Feature: Transposition support

### ISSUE THREAD

**Issue by marvinscham** [serifpersia/pianoled-arduino#27]
**Is your feature request related to a problem? Please describe.**
Many digital pianos support transposing upwards and downwards, which is useful when you want to play a song in the original key but you learned the song in a key that's easier to play or when you'd like to adjust to another musician's key. When using this together with the LED software, this creates an offset between the physically played key and the LED mapping.

**Describe the solution you'd like**
A transposition option, e.g. a slider ranging from -6 to +5/6 (typically supported transposition range) that allows countering the offset.
**Describe alternatives you've considered**
Physically moving the LED stripe. I think that's a lot more annoying, considering you have to reposition every time. It might not be possible at all for some fixed-width setups.

**Additional context**
Visual example of the problem
![roland-go-piano-88](https://github.com/serifpersia/pianoled-arduino/assets/67930021/c28c17ef-a202-4d45-a586-92431108388a)

**Comment by serifpersia** [comment]
I'm closing this as #28 pull request has been accepted into the main branch! Feel free to add more stuff you think are interesting and useful.
